/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package srms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import srms.login_frame.Signup_frame;


/**
 *
 * @author AYUSCAL SEDHAI
 */
public class Login_frame extends javax.swing.JFrame {

    
private static final String DB_URL = "jdbc:mysql://localhost:3306/sdbms";
private static final String DB_USER = "root";
private static final String DB_PASSWORD = "";


    
    
    
    /**
     * Creates new form Login_frame
     */
    public Login_frame() {
      
        initComponents();
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        PassText.setText("Enter Password");
        PassText.setForeground(Color.gray);
        PassText.setEchoChar((char) 0);
    }

    private void validateLogin(String username, String password) throws SQLException{
        Connection con = DriverManager.getConnection(DB_URL,DB_USER,DB_PASSWORD);
        String sql = "SELECT * FROM admins WHERE Username = ? AND Password =?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, username);
        ps.setString(2, password);
        ResultSet rs = ps.executeQuery();
        if (rs.next()){
            JOptionPane.showMessageDialog(this,"Login Success For Administrator " + username+".");
             new Menu_frame().setVisible(true);
             this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"Invalid Username or Password.");
            //Signup_ButActionPerformed()
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserText = new javax.swing.JTextField();
        PassText = new javax.swing.JPasswordField();
        Login_But = new javax.swing.JButton();
        Signup_But = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        showPasswordCheckbox = new java.awt.Checkbox();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Welcome", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 36), new java.awt.Color(242, 242, 242))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 36), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setText("Password:");

        UserText.setText("Enter Username");
        UserText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserTextFocusLost(evt);
            }
        });
        UserText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextActionPerformed(evt);
            }
        });

        PassText.setText("Enter Password");
        PassText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PassTextFocusLost(evt);
            }
        });
        PassText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassTextActionPerformed(evt);
            }
        });

        Login_But.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        Login_But.setText("Login");
        Login_But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButActionPerformed(evt);
            }
        });

        Signup_But.setBackground(new java.awt.Color(0, 102, 102));
        Signup_But.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        Signup_But.setForeground(new java.awt.Color(204, 204, 204));
        Signup_But.setText("SignUp Here!");
        Signup_But.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        Signup_But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup_ButActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("If Account  not registered");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Please");
        jLabel5.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Forgot Password!");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        showPasswordCheckbox.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        showPasswordCheckbox.setLabel("Show Password!");
        showPasswordCheckbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPasswordCheckboxMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                showPasswordCheckboxMouseReleased(evt);
            }
        });
        showPasswordCheckbox.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                showPasswordCheckboxComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                showPasswordCheckboxComponentShown(evt);
            }
        });
        showPasswordCheckbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showPasswordCheckboxItemStateChanged(evt);
            }
        });
        showPasswordCheckbox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                showPasswordCheckboxPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                        .addComponent(Login_But, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showPasswordCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PassText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Signup_But, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UserText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 335, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserText, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PassText, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(showPasswordCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login_But, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Signup_But))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PassTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassTextActionPerformed
        // TODO add your handling code here:   
        
    }//GEN-LAST:event_PassTextActionPerformed

    private void UserTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextActionPerformed
        // TODO add your handling code here:
          String username = UserText.getText();
    System.out.println("Username: "+ username); 
    }//GEN-LAST:event_UserTextActionPerformed

    private void UserTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserTextFocusGained
        // TODO add your handling code here:
        if(UserText.getText().equals("Enter Username")){
           UserText.setText(null);
           UserText.requestFocus();
           UserText.setForeground(Color.black);
           
        }
    }//GEN-LAST:event_UserTextFocusGained

    private void PassTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassTextFocusGained
        // TODO add your handling code here:
          String password = new String(PassText.getPassword());
    if (password.equals("Enter Password")) {
        PassText.setText(""); // Clear text immediately
        PassText.setForeground(Color.black);    
        PassText.setEchoChar('*');  // Enable masking
        
    }
    }//GEN-LAST:event_PassTextFocusGained

    private void UserTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserTextFocusLost
        // TODO add your handling code here:
        // Restore placeholder if no password is entered
    String password = new String(PassText.getPassword());
    if (password.isEmpty()) {     
        PassText.setEchoChar((char) 0);  // Disable masking
        PassText.setText("Enter Password"); // Set placeholder
        PassText.setForeground(Color.gray);
    }
          if (UserText.getText().length() == 0){
            UserText.setText("Enter Username");
            UserText.setForeground(Color.gray);
           
        }
    }//GEN-LAST:event_UserTextFocusLost

    private void PassTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassTextFocusLost
        // TODO add your handling code here:
             if (new String(PassText.getPassword()).isEmpty()){     
                PassText.setEchoChar((char)0); 
                PassText.setText("Enter Password");
                PassText.setForeground(Color.gray);
                 
             }
    }//GEN-LAST:event_PassTextFocusLost

    
    
    private void Signup_ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_ButActionPerformed
        // TODO add your handling code here:
                
             java.awt.EventQueue.invokeLater(() -> {
                 try {
                     new Signup_frame().setVisible(true);
                 } catch (ClassNotFoundException ex) {
                     Logger.getLogger(Login_frame.class.getName()).log(Level.SEVERE, null, ex);
                 }
             });
        
        
    }//GEN-LAST:event_Signup_ButActionPerformed

    private void Login_ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButActionPerformed
        // TODO add your handling code here:
        
           String username = UserText.getText();
           String password = PassText.getText();
    try {
        validateLogin(username, password);
       
    } catch (SQLException ex) {
        Logger.getLogger(Login_frame.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.dispose();
    
    }//GEN-LAST:event_Login_ButActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      new Verification_frame().setVisible(true);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showPasswordCheckboxComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_showPasswordCheckboxComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_showPasswordCheckboxComponentShown

    private void showPasswordCheckboxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_showPasswordCheckboxPropertyChange
    }//GEN-LAST:event_showPasswordCheckboxPropertyChange

    private void showPasswordCheckboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordCheckboxMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_showPasswordCheckboxMouseClicked

    private void showPasswordCheckboxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordCheckboxMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_showPasswordCheckboxMouseReleased

    private void showPasswordCheckboxComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_showPasswordCheckboxComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_showPasswordCheckboxComponentResized

    private void showPasswordCheckboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showPasswordCheckboxItemStateChanged
        // TODO add your handling code here:
         if  (showPasswordCheckbox.getState())
        {
            PassText.setEchoChar((char)0);
        }
        else if (new String(PassText.getPassword()).isEmpty()) 
        {
            PassText.setText("Enter Password");
            PassText.setForeground(Color.gray);  // Optional: Set placeholder text color
            PassText.setEchoChar((char) 0);  // Disable masking
        }   
        else {
        // If the password field is not empty, mask the password with '*'
            PassText.setEchoChar('*');  // Enable masking
    }
    }//GEN-LAST:event_showPasswordCheckboxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        new Login_frame().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_But;
    private javax.swing.JPasswordField PassText;
    private javax.swing.JButton Signup_But;
    private javax.swing.JTextField UserText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Checkbox showPasswordCheckbox;
    // End of variables declaration//GEN-END:variables

}