/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package srms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author AYUSCAL SEDHAI
 */
public class Menu_frame extends javax.swing.JFrame {

    /**
     * Creates new form Menu_frame
     */
    public Menu_frame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nr_But = new javax.swing.JButton();
        drr_But = new javax.swing.JButton();
        e_But = new javax.swing.JButton();
        fst = new javax.swing.JButton();
        rslt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Welcome", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 36), new java.awt.Color(242, 242, 242))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "SRMS Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 36), new java.awt.Color(0, 102, 102))); // NOI18N

        nr_But.setBackground(new java.awt.Color(0, 102, 102));
        nr_But.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        nr_But.setForeground(new java.awt.Color(255, 255, 255));
        nr_But.setText("NEW REGISTRATION");
        nr_But.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        nr_But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nr_ButActionPerformed(evt);
            }
        });

        drr_But.setBackground(new java.awt.Color(0, 102, 102));
        drr_But.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        drr_But.setForeground(new java.awt.Color(255, 255, 255));
        drr_But.setText("DISPLAY_SEARCH_DELETE_UPDATE RECORDS");
        drr_But.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        drr_But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drr_ButActionPerformed(evt);
            }
        });

        e_But.setBackground(new java.awt.Color(0, 102, 102));
        e_But.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        e_But.setForeground(new java.awt.Color(255, 255, 255));
        e_But.setText("LOGOUT");
        e_But.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        e_But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_ButActionPerformed(evt);
            }
        });

        fst.setBackground(new java.awt.Color(0, 102, 102));
        fst.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        fst.setForeground(new java.awt.Color(255, 255, 255));
        fst.setText("FEE STRUCTURE & ADMIT CARD");
        fst.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        fst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fstActionPerformed(evt);
            }
        });

        rslt.setBackground(new java.awt.Color(0, 102, 102));
        rslt.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        rslt.setForeground(new java.awt.Color(255, 255, 255));
        rslt.setText("RESULT UPDATE");
        rslt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        rslt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(e_But)
                    .addComponent(rslt)
                    .addComponent(fst)
                    .addComponent(nr_But)
                    .addComponent(drr_But))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(nr_But)
                .addGap(18, 18, 18)
                .addComponent(drr_But)
                .addGap(18, 18, 18)
                .addComponent(fst)
                .addGap(18, 18, 18)
                .addComponent(rslt)
                .addGap(18, 18, 18)
                .addComponent(e_But)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nr_ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nr_ButActionPerformed
        // TODO add your handling code here:
        new addRecord_frame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nr_ButActionPerformed

    private void drr_ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drr_ButActionPerformed
        // TODO add your handling code here:
        dispayRecord_frame frame = new dispayRecord_frame();
        frame.setVisible(true); // Makes the frame visible
        this.dispose();
    }//GEN-LAST:event_drr_ButActionPerformed

    private void e_ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_ButActionPerformed
        // TODO add your handling code here:
        new Login_frame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_e_ButActionPerformed

    private void fstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fstActionPerformed
        try {
            this.dispose();
            new fee_structure().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Menu_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_fstActionPerformed

    private void rsltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsltActionPerformed
       
        
    }//GEN-LAST:event_rsltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu_frame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drr_But;
    private javax.swing.JButton e_But;
    private javax.swing.JButton fst;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nr_But;
    private javax.swing.JButton rslt;
    // End of variables declaration//GEN-END:variables
}
